//! FFI bindings to libopenrtx
//!
//! These bindings are auto-generated by bindgen in build.rs

// Include the generated bindings
include!(concat!(env!("OUT_DIR"), "/libopenrtx_bindings.rs"));

// Additional helper functions

/// Convert mode integer to string
pub fn mode_to_string(mode: i32) -> &'static str {
    match mode {
        MODE_FM => "FM",
        MODE_NFM => "NFM",
        MODE_AM => "AM",
        MODE_USB => "USB",
        MODE_LSB => "LSB",
        MODE_M17 => "M17",
        MODE_DMR => "DMR",
        _ => "UNKNOWN",
    }
}

/// Format frequency in MHz with appropriate precision
pub fn format_frequency(hz: u32) -> String {
    let mhz = hz as f64 / 1_000_000.0;
    if mhz >= 1000.0 {
        format!("{:.4}", mhz)
    } else if mhz >= 100.0 {
        format!("{:.3}", mhz)
    } else {
        format!("{:.3}", mhz)
    }
}

/// Format frequency with band suffix
pub fn format_frequency_with_band(hz: u32) -> String {
    let mhz = hz as f64 / 1_000_000.0;
    let band = if mhz >= 0.1 && mhz < 30.0 {
        if mhz >= 1.6 && mhz <= 3.0 {
            "160m"
        } else if mhz >= 3.5 && mhz <= 4.0 {
            "80m"
        } else if mhz >= 7.0 && mhz <= 7.3 {
            "40m"
        } else if mhz >= 10.1 && mhz <= 10.15 {
            "30m"
        } else if mhz >= 14.0 && mhz <= 14.35 {
            "20m"
        } else if mhz >= 18.068 && mhz <= 18.168 {
            "17m"
        } else if mhz >= 21.0 && mhz <= 21.45 {
            "15m"
        } else if mhz >= 24.89 && mhz <= 24.99 {
            "12m"
        } else if mhz >= 28.0 && mhz <= 29.7 {
            "10m"
        } else if mhz >= 50.0 && mhz <= 54.0 {
            "6m"
        } else if mhz >= 144.0 && mhz <= 148.0 {
            "2m"
        } else if mhz >= 222.0 && mhz <= 225.0 {
            "1.25m"
        } else if mhz >= 420.0 && mhz <= 450.0 {
            "70cm"
        } else if mhz >= 902.0 && mhz <= 928.0 {
            "33cm"
        } else if mhz >= 1240.0 && mhz <= 1300.0 {
            "23cm"
        } else {
            ""
        }
    } else {
        ""
    };

    if band.is_empty() {
        format!("{:.4} MHz", mhz)
    } else {
        format!("{:.3} MHz ({})", mhz, band)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_format_frequency() {
        assert_eq!(format_frequency(145500000), "145.500");
        assert_eq!(format_frequency(433400000), "433.400");
        assert_eq!(format_frequency(28400000), "28.400");
    }

    #[test]
    fn test_mode_to_string() {
        assert_eq!(mode_to_string(MODE_FM), "FM");
        assert_eq!(mode_to_string(MODE_M17), "M17");
        assert_eq!(mode_to_string(99), "UNKNOWN");
    }
}